from langchain_core.messages import SystemMessage, AIMessage
from langchain_core.runnables.config import RunnableConfig
from src.agent.state import AgentState

async def report_node(state: AgentState, config: RunnableConfig) -> AgentState:
    """
    Step 6: The Report Agent.
    Takes the structured findings from Research, Data, Analysis, and Critic.
    Produces the final markdown response for the user.
    """
    from src.agent.graph import get_llm
    llm = get_llm(state)
    
    plan = "\n".join(state.get("plan", []))
    research = state.get("research_findings", {}).get("summary", "None")
    data = state.get("financial_data", {}).get("raw", "None")
    analysis = state.get("analysis_results", {}).get("findings", "None")
    critic = state.get("critic_feedback", "None")
    doc_context = state.get("document_context", "") or "None"
    mem_context = state.get("memory_context", "") or "None"
    user_query = state['messages'][0].content if state['messages'] else ""
    
    system_prompt = f"""You are the REPORT AGENT, the final step in the quant pipeline.
Your job is to synthesize all findings into a coherent, highly professional financial report for the user.

USER QUERY:
{user_query}

USER'S PERSONAL CONTEXT (remembered from past conversations):
{mem_context}

PIPELINE EXECUTION PLAN:
{plan}

0. UPLOADED DOCUMENT CONTEXT (from user's uploaded files — HIGH PRIORITY):
{doc_context}

1. RESEARCH FINDINGS (Qualitative):
{research}

2. FINANCIAL DATA (Quantitative Data):
{data}

3. ANALYSIS RESULTS (DCF, Peers, Risk):
{analysis}

4. CRITIC FEEDBACK (Risks & Confidence):
{critic}

INSTRUCTIONS:
- Write a clear, highly detailed markdown response directly answering the user's query.
- DO NOT summarize away the depth of the Research, Data, and Analysis sections. Preserve their valuable insights, numbers, detailed breakdowns, and structure!
- Synthesize the sections together smoothly, but keep all the rich content generated by the previous agents.
- Use the user's personal context to personalize the response (e.g., if they own a company, tailor insights to them).
- If uploaded document context is available and relevant, prioritize it as the primary data source.
- Emphasize the Critic's feedback regarding risks and assumptions at the end of the report.
- Do NOT hallucinate any numbers. Only use the numbers provided in the Data, Document Context, and Analysis sections.
- CRITICAL: DO NOT output any raw JSON, agent routing tags (like `RESEARCH{...}`, `DATA{...}`), or execution plans in your final response. The user only wants the final polished human-readable report!
"""
    
    try:
        res = await llm.ainvoke([SystemMessage(content=system_prompt)], config=config)
        
        # We append the final response to the message history so the frontend sees it
        new_messages = list(state.get("messages", []))
        new_messages.append(res)
        
        return {
            "messages": new_messages,
            "final_insight": res.content
        }
    except Exception as e:
        import traceback
        traceback.print_exc()
        print(f"[Report] Failed: {e}")
        fallback = AIMessage(content="Error generating final report from the multi-agent pipeline.")
        return {"messages": state["messages"] + [fallback]}
